### PR TITLE
Fix Notebook Terminal infinitely resizing

### LINKED ISSUE #383: Terminal Fit can shrink eternally
https://user-images.githubusercontent.com/16108792/230225557-1a2f6a96-95ac-4a51-96bf-f6e2a012dd4f.mp4

For some strange reason, terminal fit can end up infinitely shrinking the number of available rows.

### PR DESCRIPTION
**Pull request by mxsdev**
Fixes #383 

This includes a "fork" of the fit addon from xtermjs, where we make the requisite calculations more directly. We are potentially susceptible to breakage on a dependency update - hopefully these will get caught by e2e tests #357

### CODE REVIEW

File: src/client/fitAddon.ts [hunk 1]
```diff
@@ -0,0 +1,125 @@
+/**
```
Comment (sourishkrout) [inline src/client/fitAddon.ts:1]: I'd suggest to add some paragraphs on top here to describe how and why this version is different

File: src/client/fitAddon.ts [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+
+  public dispose(): void {}
+
+  public fit(): void {
+    const dims = this.proposeDimensions()
+    if (!dims || !this._terminal || isNaN(dims.cols) || isNaN(dims.rows)) {
+      return
+    }
+
+    // TODO: Remove reliance on private API
```
Comment (sourishkrout) [inline src/client/fitAddon.ts:68]: Interesting to see these comments literally coming from the upstream project.

**Review by sourishkrout — APPROVED** [review]
👍 LGTM
